name: 'URL Health Check -v2'
description: 'Waits for a URL to return a specific HTTP status code with retries.'
author: 'David Tayar <davidt@grasshopperlabs.io>'
inputs:
    url:
        description: 'Site URL'
        required: true
    max-attempts:
        description: 'Maximum number of attempts before failing'
        required: false
        default: '1'
    retry-delay:
        description: 'Delay between retries in milliseconds'
        required: false
        default: '10000'
    expect-status:
        description: 'Expected HTTP status code'
        required: false
        default: '200'
runs:
    using: 'docker'
    image: 'Dockerfile'
branding:
    icon: 'activity'
    color: 'white'